export type ExceptionInternalCode =
  | UserExceptions
  | TokenExceptions
  | ChatExceptions
  | FileExceptions
  | MessageExceptions
  | SendEmailExceptions
  | StorageExceptions


export enum UserExceptions {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_NOT_ALLOWED = 'USER_NOT_ALLOWED',
  USER_NOT_CREATED = 'USER_NOT_CREATED',
  USER_INVALID_CREDENTIALS = 'USER_INVALID_CREDENTIALS',
  USER_EMAIL_ALREADY_IN_USE = 'USER_EMAIL_ALREADY_IN_USE',
  USER_PHONE_ALREADY_IN_USE = 'USER_PHONE_ALREADY_IN_USE',
  USER_CPF_ALREADY_IN_USE = 'USER_CPF_ALREADY_IN_USE',
  USER_NOT_SAFETY_PASSWORD = 'USER_NOT_SAFETY_PASSWORD',
  USER_INVALID_REQUEST = 'USER_INVALID_REQUEST',
  USER_INVALID_PASSWORD = 'USER_INVALID_PASSWORD',
}

export enum TokenExceptions {
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
}

export enum ChatExceptions {
  CHAT_NOT_FOUND = 'CHAT_NOT_FOUND',
}

export enum MessageExceptions {
  MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',
}

export enum FileExceptions {
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
  FILE_ALREADY_DELETED = 'FILE_ALREADY_DELETED',
}

export enum SendEmailExceptions {
  EMAIL_SENDING_FAILED = 'EMAIL_SENDING_FAILED',
  EMAIL_LOADING_FAILED = 'EMAIL_LOADING_FAILED',
}

export enum StorageExceptions {
  STORAGE_FILE_NOT_FOUND = 'STORAGE_FILE_NOT_FOUND',
  STORAGE_URL_INVALID = 'STORAGE_URL_INVALID',
  STORAGE_URL_NOT_PROVIDED = 'STORAGE_URL_NOT_PROVIDED',
  STORAGE_KEY_NOT_PROVIDED = 'STORAGE_KEY_NOT_PROVIDED',
  STORAGE_UPLOAD_FAILED = 'STORAGE_UPLOAD_FAILED',
}
